environments:
  pypi_package:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - gocd_tools
pipelines:
  gocd_tools:
    group: pypi_package
    locking: off
    materials:
      gocd_tools_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/gocd-tools.git
        branch: main
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
    parameters:
      ARGS: ''
    template: pypi_package