environments:
  gocd_tools:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: "{{SECRET:[gocd_tools][username]}}"
      PYPI_PASSWORD: "{{SECRET:[gocd_tools][password]}}"
    pipelines:
      - gocd-tools
pipelines:
  gocd-tools:
    display_order: -1
    group: pypi_package
    label_template: ${COUNT}
    lock_behaviour: none
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      gocd_tools_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/gocd-tools.git
        branch: main
        destination: gocd-tools
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      SRC_DIRECTORY: gocd-tools
      BUILD_ARGS: install
      TEST_DIRECTORY: gocd-tools
      TEST_MAKE_TARGET: test
      TEST_ARGS: ''
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package
